README.md

This was picked up by Index Coop's developers. Our quickstart guide was out of sync with our API.

Updated the README's quickstart guide

---

src/ArcxAnalyticsSdk.ts

The `trackPagesChanges` method was submitting page events using the format `sdk.page(url)`. This is wrong. It should actually be using the format `sdk.page({ url })`. This PR addresses that issue and corrects the data structure going forward.

Fixed the autotracker not submitting the correct event schema

---

package.json
src/ArcxAnalyticsSdk.ts
src/helpers/index.ts
src/helpers/postRequest.ts
src/types.ts
test/ArcxAnalyticsSdk.test.ts
yarn.lock

The `postAnalytics` function was set as static on the object but it shouldn't have been. This pr moves it to a `helpers/` folder.
Also updating the `Window` type to include an optional `url` parameter.

Move post request helper outside of sdk class

---

README.md
package.json
src/ArcxAnalyticsSdk.ts
src/constants/config.ts
src/types.ts
test/ArcxAnalyticsSdk.test.ts
test/declarations.d.ts
tsconfig.json
yarn.lock

The `url` is used internally to track page changes, but I don't se a reason to store it on the window object, instead moving it to the class.
Also, the `attribute()` call should also support a `medium`, as it is commonly used among utm tags.

Refactor url and add medium to the attribute call

---

package.json

closes #82
Tested with the vue import as described at https://github.com/arcxmoney/analytics-sdk/issues/82#issuecomment-1355471162

Export esm and cjs correctly

---

src/ArcxAnalyticsSdk.ts
src/helpers/postRequest.ts
test/ArcxAnalyticsSdk.test.ts
test/postRequest.test.ts

Closes https://github.com/arcxmoney/analytics-sdk/issues/91

fix: avoid saving wrong identity id when api key is incorrect

---

src/ArcxAnalyticsSdk.ts

Currently there's a problem regarding automatic CONNECT and CLICK events:
- Load a page with the sdk installed where the wallet is already connected
- The CONNECT event is fired right away *while* the socket is connected. With the previous setup, an error would be thrown. However, if we just call `socket.emit(event, attributes)`, it is being buffered and sent when the connection is established so we don't lose any event.

Buffer events until the socket connection is established

---

.releaserc

When I added the `semantic-release-export-data` semantic release plugin, I added the `plugins` directive, which overwrites all the default plugins, including the npm release plugin. This PR adds them back explicitly

Add missing release plugins

---

.releaserc

From the previous run, the git tag already gets published

Remove git plugin

---

.releaserc
package.json
yarn.lock

I previously removed it, thinking that it would publish to git after publishing to NPM, but that wasn't the case because NPM assumed the position of default publish channel, resulting in the git release not being published.

Add missing git release plugin

---

src/helpers/createClientSocket.ts

As pointed in [this issue](https://github.com/socketio/socket.io/issues/1739), we need to set `websocket` as supported transport to avoid too many requests on a high-load server

Set websocket as supported transport

---

src/ArcxAnalyticsSdk.ts

Closes #124 
A disconnect event can be called twice, so ignore the second call:

Remove warning when disconnect is called a second time

---

src/ArcxAnalyticsSdk.ts
yarn.lock

The server responds with a `BadRequestError` if the `identityId` is well formatted, but doesn't exist in our db.

Refresh identity id if server responds with `BadRequestError`

---

src/ArcxAnalyticsSdk.ts
test/ArcxAnalyticsSdk.test.ts
test/constants.ts

Even though `utm_content` was present in the url, it was not passed in the `attribute()` call. This pr fixes this.

Track `utm_content` in attribute call

---

src/ArcxAnalyticsSdk.ts
test/ArcxAnalyticsProvider.test.tsx
test/ArcxAnalyticsSdk.test.ts
test/constants.ts

Add url to each event

---

.gitignore
README.md
src/ArcxAnalyticsSdk.ts
src/utils/createClientSocket.ts
test/ArcxAnalyticsSdk.test.ts
test/constants.ts

Closes #142. 
- We can get the rest of the information from the user agent string.
- Also passing the full `url` to the websocket connection string

Add screen and viewport sizes to the websocket query

---

README.md
src/ArcxAnalyticsSdk.ts
test/ArcxAnalyticsSdk.test.ts

Closes #145
Writing this PR made me realise that we're inconsistent with the naming style of our public functions. Will create a new PR to make them uniform.

Add `signedMessage()` function

---

README.md
src/ArcxAnalyticsSdk.ts
src/types/base.ts
test/ArcxAnalyticsSdk.test.ts

Closes #149
Depends on https://github.com/arcxmoney/analytics-sdk/pull/153
Not disabling automatic disconnection because it shouldn't do any harm. If the user fires `disconnect()` and we've already done it automatically, nothing will happen.

Add disconnection() method

---

src/ArcxAnalyticsSdk.ts
test/ArcxAnalyticsSdk.test.ts

I realized we had it but didn't report it which is a value that is missing given the new EventV2 schema.

Add `chainId` attribute to `TRANSACTION_TRIGGERED`

---

README.md
example/cra-script-tag/public/index.html
example/cra-script-tag/src/Web3Buttons.tsx
example/cra-script-tag/src/types/types.ts
src/ArcxAnalyticsProvider.tsx
src/ArcxAnalyticsSdk.ts
src/types/base.ts
src/utils/createClientSocket.ts
src/utils/postRequest.ts
test/ArcxAnalyticsProvider.test.tsx
test/ArcxAnalyticsSdk.test.ts
test/utils/postRequest.test.ts

- disabled automatic web3 event tracking for the npm package
- added the header `X-Library-Usage` to each request depending if the SDK is used with a script tag or npm package
- removed `setProvider()` because dApps supporting more wallets than Metamasks should manually track their web3 events (connect, transact, etc)
Closes #158 
Closes #167

Disable automatic event tracking for the npm package and add library usage header

---

src/ArcxAnalyticsSdk.ts
test/ArcxAnalyticsSdk.test.ts

The first PAGE call is fired before `window.arcx` is set, so had to accomodate for that.

Ignore reporting the library usage on the first page call

---

src/ArcxAnalyticsSdk.ts

We should never throw inside the `request()` function because this can prevent clients from executing transactions. Even though it is a valid error, we should just log it and continue - never throw.

Do not throw inside `request()`

---

src/ArcxAnalyticsSdk.ts
src/types/web3.ts
test/ArcxAnalyticsSdk.test.ts

Closes https://github.com/arcxmoney/sdk-api/issues/471
If no account was recorded, request `eth_requestAccounts` to get the connected account from the provider.

Request connected account in chain changed if no account was previously recorded

---

src/ArcxAnalyticsSdk.ts
test/ArcxAnalyticsSdk.test.ts

Do not fire a `DISCONNECT` event if `currentConnectedAccount` is undefined and emit `chainId`
instead of `chain`.
closes #179

Fix automatic disconnect events

---

src/ArcxAnalyticsProvider.tsx
src/constants/config.ts
src/types/base.ts
test/ArcxAnalyticsProvider.test.tsx

This is the result of a user request to allow them to skip initialization for non-production environments.

Add `disabled` prop to the SDK provider
