README.md

Add provider documentation to readme

---

.husky/commit-msg
.husky/pre-commit
.husky/pre-push
README.md
commitlint.config.js
package.json
yarn.lock

Add commit linter and commitizen

---

.github/workflows/release.yaml
.releaserc
package.json
yarn.lock

Adds [semantic-release](https://github.com/semantic-release/semantic-release) to the release workflow. Now when we want to trigger a release, we simply start the release workflow and the package with a decent changelog and versioning should be published.
Only the following commit types will alter the version:
- `fix`: patch release
- `feat`: minor release
- `BREAKING CHANGE:`: major release
Running `yarn commit` for each commit makes it easy to append these prefixes to your commits.

Add semantic release

---

README.md

Adds some nice badges and named commits to trigger a release.

Improve documentation and trigger release

---

package.json
src/ArcxAnalyticsSdk.ts
src/types/index.ts
src/types/web3.ts
src/types/window.d.ts
test/ArcxAnalyticsProvider.test.tsx
test/ArcxAnalyticsSdk.test.ts
test/MockEthereum.ts
yarn.lock

Closes https://github.com/arcxmoney/analytics-sdk/issues/55

chore: remove metatamask depednency

---

example/src/App.tsx
src/ArcxAnalyticsSdk.ts
test/ArcxAnalyticsProvider.test.tsx
test/ArcxAnalyticsSdk.test.ts
test/setup.ts

Decomission the use of RAF for page event tracking

---

src/ArcxAnalyticsSdk.ts
test/ArcxAnalyticsSdk.test.ts

We could do something like this to avoid using `any` types. I didn't spend too much time trying to fix the test so I skipped it, but we could fix it in the next pr

Add type to onClick event listener

---

src/ArcxAnalyticsSdk.ts
test/ArcxAnalyticsSdk.test.ts

Merged https://github.com/arcxmoney/analytics-sdk/pull/69 too early

Revert error reporting

---

src/ArcxAnalyticsSdk.ts

Fix click event error when user clicked on a SVG

---

example/cra-provider/src/TestEventButtons.tsx
example/cra-script-tag/src/TestEventButtons.tsx
example/cra-script-tag/src/TestPageButtons.tsx
src/ArcxAnalyticsSdk.ts
test/ArcxAnalyticsSdk.test.ts

https://github.com/arcxmoney/analytics-sdk/pull/69

Report errors

---

README.md

Update README: add documentation for `setProvider`, `inittialProvider` and `trackClicks`

---

src/ArcxAnalyticsSdk.ts
test/ArcxAnalyticsSdk.test.ts

Bugfix: do not modify provider.request if it is read-only

---

src/ArcxAnalyticsSdk.ts
test/ArcxAnalyticsSdk.test.ts

Prioritize window.ethereum rather than window.web3.currentProvider

---

.github/workflows/release.yaml
.releaserc
package.json
src/helpers/postRequest.ts
test/postRequest.test.ts
yarn.lock

Merge https://github.com/arcxmoney/analytics-api/pull/75 first
Closes #99
Adds the sdk version in each POST request in the header `x-sdk-version`

Attach the sdk version with each POST request in the header

---

src/ArcxAnalyticsSdk.ts
test/ArcxAnalyticsSdk.test.ts

Closes https://github.com/arcxmoney/analytics-sdk/issues/96

Remove cleaning of storage

---

src/ArcxAnalyticsSdk.ts

Closes https://github.com/arcxmoney/analytics-sdk/issues/109

feat: support hash routes to get utm parameter

---

src/ArcxAnalyticsSdk.ts
src/utils/getFullElementInfo.ts
test/ArcxAnalyticsProvider.test.tsx
test/utils/getFullElementInfo.test.ts

feat: enrich click info with full path

---

src/ArcxAnalyticsSdk.ts
test/ArcxAnalyticsProvider.test.tsx
test/ArcxAnalyticsSdk.test.ts

Closes https://github.com/arcxmoney/analytics-sdk/issues/128
I need to retest it tomorrow. But it should work as I checked

Fix: do not fire FIRST_PAGE_EVENTS on each reconnection

---

src/ArcxAnalyticsSdk.ts

refactor: update cached identity if lost

---

src/ArcxAnalyticsSdk.ts

This will include the actual error being returned by the server to rollbar. Example:

Refactor _report method to include error object in the data payload

---

README.md
src/ArcxAnalyticsSdk.ts
src/constants/config.ts
src/types/base.ts
test/ArcxAnalyticsSdk.test.ts

Remove automatic chain changed tracking and add manual `chainChanged()` function

---

src/ArcxAnalyticsSdk.ts
test/ArcxAnalyticsSdk.test.ts

Do not track password for personal_sign events

---

src/ArcxAnalyticsSdk.ts
src/constants/config.ts
src/utils/createClientSocket.ts
src/utils/generateUniqueID.ts
src/utils/index.ts
test/ArcxAnalyticsSdk.test.ts
test/constants.ts

Added an unique `sessionStorageId` to the websocket connection string.
Closes #157

Add `sessionStorageId`

---

README.md
example/cra-script-tag/.env.example

Please approve my PR oh mighty sensei 🙏🏻

chore: updated readme + env.example

---

src/ArcxAnalyticsSdk.ts
test/ArcxAnalyticsSdk.test.ts

Throw in `chain()` if account is not passed nor previously recorded
